version: "3.4"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ogwindingtree/arbor-backend:${DOCKER_TAG}
    container_name: arbor_backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./config_aggregator.json:/app/modules/config/lib/config_aggregator.json
    labels:
      kompose.service.expose: ${DOMAIN_NAME}